/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.hcahealthcare.cdm.hl7.reject;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CdmRejects extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CdmRejects\",\"namespace\":\"com.hcahealthcare.cdm.hl7.reject\",\"fields\":[{\"name\":\"process_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"message_control_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"msg_create_date_time\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"patient_mrn\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"patient_urn\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"patient_account_number\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"reject_reason\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"rejected_message_data\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"etl_firstinsert_datetime\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.String process_name;
   private java.lang.String message_control_id;
   private java.lang.String msg_create_date_time;
   private java.lang.String patient_mrn;
   private java.lang.String patient_urn;
   private java.lang.String patient_account_number;
   private java.lang.String reject_reason;
   private java.lang.String rejected_message_data;
   private java.lang.String etl_firstinsert_datetime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CdmRejects() {}

  /**
   * All-args constructor.
   */
  public CdmRejects(java.lang.String process_name, java.lang.String message_control_id, java.lang.String msg_create_date_time, java.lang.String patient_mrn, java.lang.String patient_urn, java.lang.String patient_account_number, java.lang.String reject_reason, java.lang.String rejected_message_data, java.lang.String etl_firstinsert_datetime) {
    this.process_name = process_name;
    this.message_control_id = message_control_id;
    this.msg_create_date_time = msg_create_date_time;
    this.patient_mrn = patient_mrn;
    this.patient_urn = patient_urn;
    this.patient_account_number = patient_account_number;
    this.reject_reason = reject_reason;
    this.rejected_message_data = rejected_message_data;
    this.etl_firstinsert_datetime = etl_firstinsert_datetime;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return process_name;
    case 1: return message_control_id;
    case 2: return msg_create_date_time;
    case 3: return patient_mrn;
    case 4: return patient_urn;
    case 5: return patient_account_number;
    case 6: return reject_reason;
    case 7: return rejected_message_data;
    case 8: return etl_firstinsert_datetime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: process_name = (java.lang.String)value$; break;
    case 1: message_control_id = (java.lang.String)value$; break;
    case 2: msg_create_date_time = (java.lang.String)value$; break;
    case 3: patient_mrn = (java.lang.String)value$; break;
    case 4: patient_urn = (java.lang.String)value$; break;
    case 5: patient_account_number = (java.lang.String)value$; break;
    case 6: reject_reason = (java.lang.String)value$; break;
    case 7: rejected_message_data = (java.lang.String)value$; break;
    case 8: etl_firstinsert_datetime = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'process_name' field.
   */
  public java.lang.String getProcessName() {
    return process_name;
  }

  /**
   * Sets the value of the 'process_name' field.
   * @param value the value to set.
   */
  public void setProcessName(java.lang.String value) {
    this.process_name = value;
  }

  /**
   * Gets the value of the 'message_control_id' field.
   */
  public java.lang.String getMessageControlId() {
    return message_control_id;
  }

  /**
   * Sets the value of the 'message_control_id' field.
   * @param value the value to set.
   */
  public void setMessageControlId(java.lang.String value) {
    this.message_control_id = value;
  }

  /**
   * Gets the value of the 'msg_create_date_time' field.
   */
  public java.lang.String getMsgCreateDateTime() {
    return msg_create_date_time;
  }

  /**
   * Sets the value of the 'msg_create_date_time' field.
   * @param value the value to set.
   */
  public void setMsgCreateDateTime(java.lang.String value) {
    this.msg_create_date_time = value;
  }

  /**
   * Gets the value of the 'patient_mrn' field.
   */
  public java.lang.String getPatientMrn() {
    return patient_mrn;
  }

  /**
   * Sets the value of the 'patient_mrn' field.
   * @param value the value to set.
   */
  public void setPatientMrn(java.lang.String value) {
    this.patient_mrn = value;
  }

  /**
   * Gets the value of the 'patient_urn' field.
   */
  public java.lang.String getPatientUrn() {
    return patient_urn;
  }

  /**
   * Sets the value of the 'patient_urn' field.
   * @param value the value to set.
   */
  public void setPatientUrn(java.lang.String value) {
    this.patient_urn = value;
  }

  /**
   * Gets the value of the 'patient_account_number' field.
   */
  public java.lang.String getPatientAccountNumber() {
    return patient_account_number;
  }

  /**
   * Sets the value of the 'patient_account_number' field.
   * @param value the value to set.
   */
  public void setPatientAccountNumber(java.lang.String value) {
    this.patient_account_number = value;
  }

  /**
   * Gets the value of the 'reject_reason' field.
   */
  public java.lang.String getRejectReason() {
    return reject_reason;
  }

  /**
   * Sets the value of the 'reject_reason' field.
   * @param value the value to set.
   */
  public void setRejectReason(java.lang.String value) {
    this.reject_reason = value;
  }

  /**
   * Gets the value of the 'rejected_message_data' field.
   */
  public java.lang.String getRejectedMessageData() {
    return rejected_message_data;
  }

  /**
   * Sets the value of the 'rejected_message_data' field.
   * @param value the value to set.
   */
  public void setRejectedMessageData(java.lang.String value) {
    this.rejected_message_data = value;
  }

  /**
   * Gets the value of the 'etl_firstinsert_datetime' field.
   */
  public java.lang.String getEtlFirstinsertDatetime() {
    return etl_firstinsert_datetime;
  }

  /**
   * Sets the value of the 'etl_firstinsert_datetime' field.
   * @param value the value to set.
   */
  public void setEtlFirstinsertDatetime(java.lang.String value) {
    this.etl_firstinsert_datetime = value;
  }

  /** Creates a new CdmRejects RecordBuilder */
  public static com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder newBuilder() {
    return new com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder();
  }
  
  /** Creates a new CdmRejects RecordBuilder by copying an existing Builder */
  public static com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder newBuilder(com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder other) {
    return new com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder(other);
  }
  
  /** Creates a new CdmRejects RecordBuilder by copying an existing CdmRejects instance */
  public static com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder newBuilder(com.hcahealthcare.cdm.hl7.reject.CdmRejects other) {
    return new com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder(other);
  }
  
  /**
   * RecordBuilder for CdmRejects instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CdmRejects>
    implements org.apache.avro.data.RecordBuilder<CdmRejects> {

    private java.lang.String process_name;
    private java.lang.String message_control_id;
    private java.lang.String msg_create_date_time;
    private java.lang.String patient_mrn;
    private java.lang.String patient_urn;
    private java.lang.String patient_account_number;
    private java.lang.String reject_reason;
    private java.lang.String rejected_message_data;
    private java.lang.String etl_firstinsert_datetime;

    /** Creates a new Builder */
    private Builder() {
      super(com.hcahealthcare.cdm.hl7.reject.CdmRejects.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.process_name)) {
        this.process_name = data().deepCopy(fields()[0].schema(), other.process_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message_control_id)) {
        this.message_control_id = data().deepCopy(fields()[1].schema(), other.message_control_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.msg_create_date_time)) {
        this.msg_create_date_time = data().deepCopy(fields()[2].schema(), other.msg_create_date_time);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.patient_mrn)) {
        this.patient_mrn = data().deepCopy(fields()[3].schema(), other.patient_mrn);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.patient_urn)) {
        this.patient_urn = data().deepCopy(fields()[4].schema(), other.patient_urn);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.patient_account_number)) {
        this.patient_account_number = data().deepCopy(fields()[5].schema(), other.patient_account_number);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.reject_reason)) {
        this.reject_reason = data().deepCopy(fields()[6].schema(), other.reject_reason);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.rejected_message_data)) {
        this.rejected_message_data = data().deepCopy(fields()[7].schema(), other.rejected_message_data);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.etl_firstinsert_datetime)) {
        this.etl_firstinsert_datetime = data().deepCopy(fields()[8].schema(), other.etl_firstinsert_datetime);
        fieldSetFlags()[8] = true;
      }
    }
    
    /** Creates a Builder by copying an existing CdmRejects instance */
    private Builder(com.hcahealthcare.cdm.hl7.reject.CdmRejects other) {
            super(com.hcahealthcare.cdm.hl7.reject.CdmRejects.SCHEMA$);
      if (isValidValue(fields()[0], other.process_name)) {
        this.process_name = data().deepCopy(fields()[0].schema(), other.process_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message_control_id)) {
        this.message_control_id = data().deepCopy(fields()[1].schema(), other.message_control_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.msg_create_date_time)) {
        this.msg_create_date_time = data().deepCopy(fields()[2].schema(), other.msg_create_date_time);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.patient_mrn)) {
        this.patient_mrn = data().deepCopy(fields()[3].schema(), other.patient_mrn);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.patient_urn)) {
        this.patient_urn = data().deepCopy(fields()[4].schema(), other.patient_urn);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.patient_account_number)) {
        this.patient_account_number = data().deepCopy(fields()[5].schema(), other.patient_account_number);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.reject_reason)) {
        this.reject_reason = data().deepCopy(fields()[6].schema(), other.reject_reason);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.rejected_message_data)) {
        this.rejected_message_data = data().deepCopy(fields()[7].schema(), other.rejected_message_data);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.etl_firstinsert_datetime)) {
        this.etl_firstinsert_datetime = data().deepCopy(fields()[8].schema(), other.etl_firstinsert_datetime);
        fieldSetFlags()[8] = true;
      }
    }

    /** Gets the value of the 'process_name' field */
    public java.lang.String getProcessName() {
      return process_name;
    }
    
    /** Sets the value of the 'process_name' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder setProcessName(java.lang.String value) {
      validate(fields()[0], value);
      this.process_name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'process_name' field has been set */
    public boolean hasProcessName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'process_name' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder clearProcessName() {
      process_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'message_control_id' field */
    public java.lang.String getMessageControlId() {
      return message_control_id;
    }
    
    /** Sets the value of the 'message_control_id' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder setMessageControlId(java.lang.String value) {
      validate(fields()[1], value);
      this.message_control_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'message_control_id' field has been set */
    public boolean hasMessageControlId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'message_control_id' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder clearMessageControlId() {
      message_control_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'msg_create_date_time' field */
    public java.lang.String getMsgCreateDateTime() {
      return msg_create_date_time;
    }
    
    /** Sets the value of the 'msg_create_date_time' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder setMsgCreateDateTime(java.lang.String value) {
      validate(fields()[2], value);
      this.msg_create_date_time = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'msg_create_date_time' field has been set */
    public boolean hasMsgCreateDateTime() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'msg_create_date_time' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder clearMsgCreateDateTime() {
      msg_create_date_time = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'patient_mrn' field */
    public java.lang.String getPatientMrn() {
      return patient_mrn;
    }
    
    /** Sets the value of the 'patient_mrn' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder setPatientMrn(java.lang.String value) {
      validate(fields()[3], value);
      this.patient_mrn = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'patient_mrn' field has been set */
    public boolean hasPatientMrn() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'patient_mrn' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder clearPatientMrn() {
      patient_mrn = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'patient_urn' field */
    public java.lang.String getPatientUrn() {
      return patient_urn;
    }
    
    /** Sets the value of the 'patient_urn' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder setPatientUrn(java.lang.String value) {
      validate(fields()[4], value);
      this.patient_urn = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'patient_urn' field has been set */
    public boolean hasPatientUrn() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'patient_urn' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder clearPatientUrn() {
      patient_urn = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'patient_account_number' field */
    public java.lang.String getPatientAccountNumber() {
      return patient_account_number;
    }
    
    /** Sets the value of the 'patient_account_number' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder setPatientAccountNumber(java.lang.String value) {
      validate(fields()[5], value);
      this.patient_account_number = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'patient_account_number' field has been set */
    public boolean hasPatientAccountNumber() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'patient_account_number' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder clearPatientAccountNumber() {
      patient_account_number = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'reject_reason' field */
    public java.lang.String getRejectReason() {
      return reject_reason;
    }
    
    /** Sets the value of the 'reject_reason' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder setRejectReason(java.lang.String value) {
      validate(fields()[6], value);
      this.reject_reason = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'reject_reason' field has been set */
    public boolean hasRejectReason() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'reject_reason' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder clearRejectReason() {
      reject_reason = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'rejected_message_data' field */
    public java.lang.String getRejectedMessageData() {
      return rejected_message_data;
    }
    
    /** Sets the value of the 'rejected_message_data' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder setRejectedMessageData(java.lang.String value) {
      validate(fields()[7], value);
      this.rejected_message_data = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'rejected_message_data' field has been set */
    public boolean hasRejectedMessageData() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'rejected_message_data' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder clearRejectedMessageData() {
      rejected_message_data = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'etl_firstinsert_datetime' field */
    public java.lang.String getEtlFirstinsertDatetime() {
      return etl_firstinsert_datetime;
    }
    
    /** Sets the value of the 'etl_firstinsert_datetime' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder setEtlFirstinsertDatetime(java.lang.String value) {
      validate(fields()[8], value);
      this.etl_firstinsert_datetime = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'etl_firstinsert_datetime' field has been set */
    public boolean hasEtlFirstinsertDatetime() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'etl_firstinsert_datetime' field */
    public com.hcahealthcare.cdm.hl7.reject.CdmRejects.Builder clearEtlFirstinsertDatetime() {
      etl_firstinsert_datetime = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public CdmRejects build() {
      try {
        CdmRejects record = new CdmRejects();
        record.process_name = fieldSetFlags()[0] ? this.process_name : (java.lang.String) defaultValue(fields()[0]);
        record.message_control_id = fieldSetFlags()[1] ? this.message_control_id : (java.lang.String) defaultValue(fields()[1]);
        record.msg_create_date_time = fieldSetFlags()[2] ? this.msg_create_date_time : (java.lang.String) defaultValue(fields()[2]);
        record.patient_mrn = fieldSetFlags()[3] ? this.patient_mrn : (java.lang.String) defaultValue(fields()[3]);
        record.patient_urn = fieldSetFlags()[4] ? this.patient_urn : (java.lang.String) defaultValue(fields()[4]);
        record.patient_account_number = fieldSetFlags()[5] ? this.patient_account_number : (java.lang.String) defaultValue(fields()[5]);
        record.reject_reason = fieldSetFlags()[6] ? this.reject_reason : (java.lang.String) defaultValue(fields()[6]);
        record.rejected_message_data = fieldSetFlags()[7] ? this.rejected_message_data : (java.lang.String) defaultValue(fields()[7]);
        record.etl_firstinsert_datetime = fieldSetFlags()[8] ? this.etl_firstinsert_datetime : (java.lang.String) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
