CREATE MULTISET TABLE EDWCDM_STAGING.CDM_AVIS_STAGING,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
sending_facility VARCHAR(35) ,
sending_application VARCHAR(35) ,
patient_mrn VARCHAR(35) ,
patient_urn VARCHAR(35) ,
patient_account_number VARCHAR(35) ,
date_time_of_birth VARCHAR(35) ,
patient_family_name VARCHAR(35) ,
patient_given_name VARCHAR(35) ,
sex VARCHAR(35) ,
date_time_of_message VARCHAR(35) ,
hl7_type VARCHAR(35) ,
message_event VARCHAR(35) ,
message_control_id VARCHAR(35) ,
processing_id VARCHAR(35) ,
version_id VARCHAR(35) ,
character_set VARCHAR(35) ,
patient_class VARCHAR(35) ,
assigned_patient_location VARCHAR(35) ,
obsv_date_time_num VARCHAR(35) ,
relevant_clinical_information VARCHAR(35) ,
set_id VARCHAR(35) ,
value_type VARCHAR(35) ,
obsv_id VARCHAR(35) ,
obsv_value VARCHAR(35) ,
units VARCHAR(35) ,
obsv_result_status VARCHAR(35) ,
user_defined_access_checks VARCHAR(35) ,
date_time_of_the_obsv VARCHAR(35) ,
deviceType VARCHAR(35) ,
assigned_patient_location_point_of_care VARCHAR(35) ,
assigned_patient_location_point_of_care_namespace_id VARCHAR(35) ,
assigned_patient_location_point_of_care_universal_id VARCHAR(35) ,
assigned_patient_location_point_of_care_universal_id_type VARCHAR(35) ,
assigned_patient_location_room VARCHAR(35) ,
assigned_patient_location_room_namespace_id VARCHAR(35) ,
assigned_patient_location_room_universal_id VARCHAR(35) ,
assigned_patient_location_room_universal_id_type VARCHAR(35) ,
assigned_patient_location_bed VARCHAR(35) ,
assigned_patient_location_bed_namespace_id VARCHAR(35) ,
assigned_patient_location_bed_universal_id VARCHAR(35) ,
assigned_patient_location_bed_universal_id_type VARCHAR(35) ,
assigned_patient_location_facility VARCHAR(35) ,
assigned_patient_location_facility_namespace_id VARCHAR(35) ,
assigned_patient_location_facility_universal_id VARCHAR(35) ,
assigned_patient_location_facility_universal_id_type VARCHAR(35) ,
assigned_patient_location_location_status VARCHAR(35) ,
assigned_patient_location_person_location_type VARCHAR(35) ,
assigned_patient_location_building VARCHAR(35) ,
assigned_patient_location_building_namespace_id VARCHAR(35) ,
assigned_patient_location_building_universal_id VARCHAR(35) ,
assigned_patient_location_building_universal_id_type VARCHAR(35) ,
assigned_patient_location_floor VARCHAR(35) ,
assigned_patient_location_floor_namespace_id VARCHAR(35) ,
assigned_patient_location_floor_universal_id VARCHAR(35) ,
assigned_patient_location_floor_universal_id_type VARCHAR(35) ,
assigned_patient_location_location_description VARCHAR(35) ,
assigned_patient_location_comprehensive_location_id VARCHAR(35) ,
assigned_patient_location_comprehensive_location_id_entity_id VARCHAR(35) ,
assigned_patient_location_comprehensive_location_id_namespace_id VARCHAR(35) ,
assigned_patient_location_comprehensive_location_id_universal_id VARCHAR(35) ,
assigned_patient_location_comprehensive_location_id_universal_id_type VARCHAR(35) ,
assigned_patient_location_assigning_authority_for_location VARCHAR(35) ,
assigned_patient_location_assigning_authority_for_location_namespace_id VARCHAR(35) ,
assigned_patient_location_assigning_authority_for_location_universal_id VARCHAR(35) ,
assigned_patient_location_assigning_authority_for_location_universal_id_type VARCHAR(35) ,
etl_insert_date_time VARCHAR(35)
)
 PRIMARY INDEX mrn_facility ( sending_facility ,
patient_mrn );